# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.27.3
_src_path: gh:seedcase-project/template-data-package
cc0_license: true
copyright_year: '2026'
for_seedcase: true
github_repo: questionnaire-data
github_user: dp-next
hosting_provider: gh-pages
