project:
  type: dp-next-theme

website:
  title: "DP-Next Questionnaire Data Package"
  site-url: "https://dp-next.github.io/wp3-d-quest"
  repo-url: "https://github.com/dp-next/wp3-d-quest"
  # TODO: Set favicon if relevant.
  # favicon: ""
  navbar:
    # TODO: Add logo and logo-alt
    # logo: ""
    # logo-alt: ""
    pinned: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Data Package"
        href: docs/index.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/wp3-d-quest"
        aria-label: "GitHub icon: Source repository"
  sidebar:
    contents:
      - index.qmd
      - docs/index.qmd

format: dp-next-theme-html
