project:
  type: dp-next-theme

website:
  title: "DP-Next Questionnaire Data Package"
  site-url: "https://dp-next.github.io/questionnaire-data"
  repo-url: "https://github.com/dp-next/questionnaire-data"
  # TODO: Set favicon if relevant.
  # favicon: ""
  navbar:
    # TODO: Add logo and logo-alt
    # logo: ""
    # logo-alt: ""
    pinned: true
    left:
      - text: "Overview"
        href: index.qmd
      - text: "Protocol"
        href: docs/protocol.qmd
      - text: "Data Package"
        href: docs/metadata/index.qmd
    tools:
      - icon: github
        href: "https://github.com/dp-next/questionnaire-data"
        aria-label: "GitHub icon: Source repository"
  sidebar:
    - id: overview
      style: "floating"
      contents:
        - text: "Overview"
          href: index.qmd
        - CONTRIBUTING.md
        # - CHANGELOG.md
    - id: package
      contents:
        - text: "Package"
          href: docs/metadata/index.qmd
        - auto: docs/metadata/resources/

format: dp-next-theme-html
